### ISSUE TITLE
Python 3.5.0

### ISSUE THREAD

**Issue by kuri65536** [kuri65536/python-for-android#105]
follow to new release of python3.

**Comment by kuri65536** [comment]
Here is problem: https://bugs.python.org/issue22625

**Comment by kuri65536** [comment]
Here is problem: python3
=> work around:
1. define PYTHON_FOR_BUILD = $(HOSTPYTHON)/bin/python3 in Makefile

**Comment by kuri65536** [comment]
Here is problem: compilation will failed with 'no such file: _multiprocessing/multiprocessing.c'

**Comment by kuri65536** [comment]
This is 1st version of Python-3.6.0, but not tested yet.

[python3_extras_r24a.zip](https://github.com/kuri65536/python-for-android/files/705490/python3_extras_r24a.zip)
[python3_r24a.zip](https://github.com/kuri65536/python-for-android/files/705491/python3_r24a.zip)
[python3_r24a_x86.zip](https://github.com/kuri65536/python-for-android/files/705493/python3_r24a_x86.zip)
[python3_scripts_r24a.zip](https://github.com/kuri65536/python-for-android/files/705492/python3_scripts_r24a.zip)

**Comment by kuri65536** [comment]
Now work in progress...

```
n7000 lib # sh /storage/sdcard0/python3.sh 
/storage/sdcard0/python3.sh[20]: python: not found
Could not find platform independent libraries <prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Python 3.6.0 (default, Jan 20 2017, 08:06:36) 
[GCC 4.9 20140827 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> ls
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ls' is not defined
>>> dir
<built-in function dir>
>>> import ensure_pip
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ensure_pip'
>>> import pip
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pip'
>>> print("%d" % 111_222_333_444)
111222333444
```

New feature "_" worked.
