### ISSUE TITLE
Append pip module in python_extras package.

### ISSUE THREAD

**Issue by kuri65536** [kuri65536/python-for-android#131]

**Comment by kuri65536** [comment]
I tested ensurepip and pip with python3.6.0 for android.
It worked but stalled after install (maybe lockfile does not work in FAT filesystem.)

```
n7000 com.googlecode.python3forandroid # echo $HOME
/sdcard
n7000 com.googlecode.python3forandroid # export HOME=`pwd`
n7000 ~ # echo $HOME
/sdcard/com.googlecode.python3forandroid
n7000 ~ # bash ../python3.sh -m ensurepip --user
../python3.sh: line 11: python: command not found
Could not find platform independent libraries <prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
WARNING:root:cert file changed, android system have no-compatibles with python:/mnt/sdcard/com.googlecode.python3forandroid/cacert.pem
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-9.0.1 setuptools-28.8.0

n7000 ~ # bash ../python3.sh                    
../python3.sh: line 11: python: command not found
Could not find platform independent libraries <prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Python 3.6.0 (default, Jan 22 2017, 21:34:19) 
[GCC 4.9 20140827 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.append("/sdcard/com.googlecode.python3forandroid/.local/lib/python3.6/site-packages")
>>> import pip
WARNING:root:cert file changed, android system have no-compatibles with python:/mnt/sdcard/com.googlecode.python3forandroid/cacert.pem
>>> pip.main(["install", "--user", "requests"])
Requirement already satisfied: requests in ./.local/lib/python3.6/site-packages

^CTraceback (most recent call last):
  File "/mnt/sdcard/com.googlecode.python3forandroid/.local/lib/python3.6/site-packages/pip/_vendor/lockfile/linklockfile.py", line 31, in acquire
    os.link(self.unique_name, self.lock_file)
OSError: [Errno 38] Function not implemented: '/mnt/sdcard/com.googlecode.python3forandroid/.cache/pip/localhost-40119534.14067173684091' -> '/mnt/sdcard/com
.googlecode.python3forandroid/.cache/pip/selfcheck.json.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/sdcard/com.googlecode.python3forandroid/.local/lib/python3.6/site-packages/pip/__init__.py", line 233, in main
    return command.main(cmd_args)
  File "/mnt/sdcard/com.googlecode.python3forandroid/.local/lib/python3.6/site-packages/pip/basecommand.py", line 252, in main
    pip_version_check(session)
  File "/mnt/sdcard/com.googlecode.python3forandroid/.local/lib/python3.6/site-packages/pip/utils/outdated.py", line 138, in pip_version_check
    state.save(pypi_version, current_time)
  File "/mnt/sdcard/com.googlecode.python3forandroid/.local/lib/python3.6/site-packages/pip/utils/outdated.py", line 71, in save
    with lockfile.LockFile(self.statefile_path):
  File "/mnt/sdcard/com.googlecode.python3forandroid/.local/lib/python3.6/site-packages/pip/_vendor/lockfile/__init__.py", line 197, in __enter__
    self.acquire()
  File "/mnt/sdcard/com.googlecode.python3forandroid/.local/lib/python3.6/site-packages/pip/_vendor/lockfile/linklockfile.py", line 50, in acquire
    time.sleep(timeout is not None and timeout / 10 or 0.1)
KeyboardInterrupt
>>> pip.main(["install", "--user", "beautifulsoup4"])
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.5.3-py3-none-any.whl (85kB)
    100% |################################| 92kB 173kB/s 
Installing collected packages: beautifulsoup4
Successfully installed beautifulsoup4-4.5.3

^CTraceback (most recent call last):
  File "/mnt/sdcard/com.googlecode.python3forandroid/.local/lib/python3.6/site-packages/pip/_vendor/lockfile/linklockfile.py", line 31, in acquire
    os.link(self.unique_name, self.lock_file)
OSError: [Errno 38] Function not implemented: '/mnt/sdcard/com.googlecode.python3forandroid/.cache/pip/localhost-40119534.14067173684091' -> '/mnt/sdcard/com.googlecode.python3forandroid/.cache/pip/selfcheck.json.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/sdcard/com.googlecode.python3forandroid/.local/lib/python3.6/site-packages/pip/__init__.py", line 233, in main
    return command.main(cmd_args)
  File "/mnt/sdcard/com.googlecode.python3forandroid/.local/lib/python3.6/site-packages/pip/basecommand.py", line 252, in main
    pip_version_check(session)
  File "/mnt/sdcard/com.googlecode.python3forandroid/.local/lib/python3.6/site-packages/pip/utils/outdated.py", line 138, in pip_version_check
    state.save(pypi_version, current_time)
  File "/mnt/sdcard/com.googlecode.python3forandroid/.local/lib/python3.6/site-packages/pip/utils/outdated.py", line 71, in save
    with lockfile.LockFile(self.statefile_path):
  File "/mnt/sdcard/com.googlecode.python3forandroid/.local/lib/python3.6/site-packages/pip/_vendor/lockfile/__init__.py", line 197, in __enter__
    self.acquire()
  File "/mnt/sdcard/com.googlecode.python3forandroid/.local/lib/python3.6/site-packages/pip/_vendor/lockfile/linklockfile.py", line 50, in acquire
    time.sleep(timeout is not None and timeout / 10 or 0.1)
KeyboardInterrupt
>>> import bs4
```

**Comment by kuri65536** [comment]
I tested in /data/local (not FAT filesystem)
and pip works fine.

```
n7000:/ # cd /data/local/abc
n7000:/data/local/abc # export HOME=`pwd`
n7000:/data/local/abc # bash /sdcard/python3.sh -m ensurepip --user
/sdcard/python3.sh: line 11: python: command not found
Could not find platform independent libraries <prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
WARNING:root:cert file changed, android system have no-compatibles with python:/mnt/sdcard/com.googlecode.python3forandroid/cacert.pem
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-9.0.1 setuptools-28.8.0
n7000:/data/local/abc # echo $HOME
/data/local/abc
n7000:/data/local/abc # ls .local
bin  lib  
n7000:/data/local/abc # ls .local/lib/python3.6/site-packages                                                                                               
__pycache__  easy_install.py  pip  pip-9.0.1.dist-info  pkg_resources  setuptools  setuptools-28.8.0.dist-info  
n7000:/data/local/abc # bash /sdcard/python3.sh                                                                                                             
/sdcard/python3.sh: line 11: python: command not found
Could not find platform independent libraries <prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Python 3.6.0 (default, Jan 22 2017, 21:34:19) 
[GCC 4.9 20140827 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.append("/data/local/abc/.local/lib/python3.6/site-packages")
>>> import pip
WARNING:root:cert file changed, android system have no-compatibles with python:/mnt/sdcard/com.googlecode.python3forandroid/cacert.pem
>>> pip.main(["install", "--user", "requests"])
Collecting requests
  Downloading requests-2.13.0-py2.py3-none-any.whl (584kB)
    100% |################################| 593kB 164kB/s 
Installing collected packages: requests
Successfully installed requests-2.13.0
>>> import requests
>>> r = requests.get("http://www.python.org")
>>> r.status_code
200
```

**Comment by kuri65536** [comment]
as @gauravssnl suggested,
python3forandroid next release will be shipped with ensurepip.
I tested next release and pip worked fine.

But launching pip is still tricky.

- need lockfile, FAT may not work.
- specify PYTHONPATH, it can be included in python3.sh

**Comment by gauravssnl** [comment]
Thanks a lot for considering my suggestion about adding pip support to python for Android.

**Comment by kuri65536** [comment]
lockfile problem same as:
    - https://github.com/pypa/pip/issues/2993
    - https://github.com/pypa/pip/issues/3076
    - https://github.com/pypa/pip/issues/2765

Maybe monkey patching to pip fix it.
I'm trying to renewal pip_console.py3 now.

**Comment by kuri65536** [comment]
finished update pip_console.py3.
It is very difficult to unload the "ensurepip's tempolary pip"...
user must restart this script if missing pip module.

```
n7000 ~ # bash python3.sh  pip_console.py3 
python3.sh: line 11: python: command not found
Could not find platform independent libraries <prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
WARNING:root:cert file changed, android system have no-compatibles with python:/mnt/sdcard/com.googlecode.python3forandroid/cacert.pem
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-9.0.1 setuptools-28.8.0
now pip is ready. restart pip_console.py3 script
n7000 ~ # bash python3.sh  pip_console.py3 
python3.sh: line 11: python: command not found
Could not find platform independent libraries <prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
WARNING:root:cert file changed, android system have no-compatibles with python:/mnt/sdcard/com.googlecode.python3forandroid/cacert.pem
Input pip commands, ie: pip install {module}
  for quit, type: quit, cancel or exit
--> install requests
Collecting requests
  Using cached requests-2.13.0-py2.py3-none-any.whl
Installing collected packages: requests
Successfully installed requests-2.13.0
-->         
```

**Comment by kuri65536** [comment]
finished update pip_console.py3.
It is very difficult to unload the "ensurepip's tempolary pip"...
user must restart this script if missing pip module.

command::
```
n7000 ~ # bash python3.sh  pip_console.py3
n7000 ~ # bash python3.sh  pip_console.py3
--> install requests
--> exit
```

output log::
```
n7000 ~ # bash python3.sh  pip_console.py3
WARNING:root:cert file changed, android system have no-compatibles with python:/mnt/sdcard/com.googlecode.python3forandroid/cacert.pem
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-9.0.1 setuptools-28.8.0
now pip is ready. restart pip_console.py3 script
n7000 ~ # bash python3.sh  pip_console.py3
WARNING:root:cert file changed, android system have no-compatibles with python:/mnt/sdcard/com.googlecode.python3forandroid/cacert.pem
Input pip commands, ie: pip install {module}
  for quit, type: quit, cancel or exit
--> install requests
Collecting requests
  Using cached requests-2.13.0-py2.py3-none-any.whl
Installing collected packages: requests
Successfully installed requests-2.13.0
--> exit
```

**Comment by gauravssnl** [comment]
Well done.Finally,you are successfull .Here is my another suggestion. First time **pip** installation command can be set as : 
**$python3.sh  pip_console.py3 install pip **
To install any modules(say **requests** ) via **pip** , we can use command:
**$python3.sh pip_console.py3 install requests**
we can do this by using **sys.argv** to take command line arguments as input to **pip_console.py3** file.
what do you think about this idea???

**Comment by kuri65536** [comment]
pip_console.py3 is already match to your idea.
(but I did not tested)

Try `$python3.sh pip_console.py3 install requests` right now.

Thank you.

```python
if __name__ == "__main__":
    readline
    dname = setup_dir()
    pip_monkeypatch(dname)
    if pip_rooting(dname):
        sys.exit(0)
    main(list(sys.argv))
#
```

**Comment by gauravssnl** [comment]
okay.
