### ISSUE TITLE
Unknown RPC error when trying to access USB 

### ISSUE THREAD

**Issue by foxtrotmike** [kuri65536/python-for-android#94]
I am trying o access the USB using SL4A r6 with Python 3.4.3 but I get unknown RPC error. Here is the code that will recreate this:

import android
droid = android.Android()
droid.usbserialGetDeviceList()

This will produce: 

com.googlecode.android_scripting.rpc.RpcError: Unknown RPC.

**Comment by kuri65536** [comment]
No problem with RPC erorr, but my device(emulator) did not have 
USB Host function and failed with it.

Did you use SL4A r6x04?

```log
V/sl4a.JsonRpcServer:74( 2148): Received: {"params": ["a46756ab-9cc1-4a3d-96a3-dae2e5f54e44"], "id": 0, "method": "_authenticate"}
V/sl4a.JsonRpcServer:117( 2148): Sent: {"id":0,"result":true,"error":null}
V/sl4a.JsonRpcServer:74( 2148): Received: {"params": [], "id": 1, "method": "usbserialGetDeviceList"}
E/sl4a.JsonRpcServer:101( 2148): Invocation error.
E/sl4a.JsonRpcServer:101( 2148): java.lang.NullPointerException: Attempt to invoke interface method 'void android.hardware.usb.IUsbManager.getDeviceList(android.os.Bundle)' on a null object reference
E/sl4a.JsonRpcServer:101( 2148): 	at android.hardware.usb.UsbManager.getDeviceList(UsbManager.java:243)
E/sl4a.JsonRpcServer:101( 2148): 	at com.googlecode.android_scripting.facade.USBHostSerialFacade.usbserialGetDeviceList(USBHostSerialFacade.java:107)
E/sl4a.JsonRpcServer:101( 2148): 	at java.lang.reflect.Method.invoke(Native Method)
E/sl4a.JsonRpcServer:101( 2148): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/sl4a.JsonRpcServer:101( 2148): 	at com.googlecode.android_scripting.jsonrpc.RpcReceiverManager.invoke(RpcReceiverManager.java:87)
E/sl4a.JsonRpcServer:101( 2148): 	at com.googlecode.android_scripting.facade.FacadeManager.invoke(FacadeManager.java:58)
E/sl4a.JsonRpcServer:101( 2148): 	at com.googlecode.android_scripting.rpc.MethodDescriptor.invoke(MethodDescriptor.java:109)
E/sl4a.JsonRpcServer:101( 2148): 	at com.googlecode.android_scripting.jsonrpc.JsonRpcServer.handleConnection(JsonRpcServer.java:99)
E/sl4a.JsonRpcServer:101( 2148): 	at com.googlecode.android_scripting.SimpleServer$ConnectionThread.run(SimpleServer.java:91)
V/sl4a.JsonRpcServer:117( 2148): Sent: {"id":1,"result":null,"error":"java.lang.NullPointerException: Attempt to invoke interface method 'void android.hardware.usb.IUsbManager.getDeviceList(android.os.Bundle)' on a null object reference"}
```

**Comment by kuri65536** [comment]
BTW, I found [the blog](http://newscentral.exsees.com/item/6ededc236fe4a68bda28f9aa26e9d0f8-52265088de2e48354b40f437061df2eb).
Android 5.0 changed the behavior in device that has no USB HOST function...
Are there any other changes in 5.0> ?

**Comment by kuri65536** [comment]
Sorry  foxtrotmike, I confirmd with x86 apk.
Current arm apk reproduce the Unknown RPC error.
It will be fixed and confirmed soon...

**Comment by kuri65536** [comment]
Re-uploaded Rev. https://github.com/kuri65536/sl4a/commit/ba56dd3f6d5208ab011d8484c099e5f285d398b4 binary.
Please try it again.
